steps:
  - label: ":github: Import trigger-selected workflow"
    key: "github-actions-importer"
    timeout_in_minutes: 10
    plugins:
      - github-actions#v0.13.0:
          workflow: "$$BUILDKITE_GITHUB_WORKFLOW_PATH"
          version: "0.35.1"
